version: "3"
services:
  app:
    image: pudding/docker-app:zip-image-half-spliter-20231110-2005
    tty: true
    command: node /app/split-zip-image-to-half.js "/input/[INPUT]"
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - [SOURCE]:/input/